# site information
authors: "Jeremy Wong"
description: "© 2015-17 Craft By Zen"
github_username: "jermspeaks"
twitter_username: "jermspeaks"
navigation:
# - text: Home
#   url: /
# - text: Letter Archive
#   url: /letters/
# - text: Blog
#   url: /blog/
# - text: Resume
#   url: /resume/
- text: About
  url: /about/
- text: Writing
  url: /writing/
- text: Codes
  url: /projects/
- text: Talks
  url: /talks/

projects:
  - name: Zika VR
    description: As part of National Day of Civic Hacking 2016,
      we formed a team that created a virtual reality prototype
      to enable the public to better learn about the Zika virus –
      the nature of the pathogen, its health consequences,
      potential breeding grounds of Zika infected mosquitos,
      and effective Zika prevention techniques.
    project_link: https://jermspeaks.github.io/webvr-demo/?polyfill=1
    image: /assets/images/webvr-demo.png
    url: /projects/zika
  - name: Flitr
    description: Flight is a social networking playground
      where users post their profiles and show their pictures.
      It is the penultimate project with DevBootcamp
    # project_link: https://github.com/simongondeck/flight-social-network
    image: /assets/images/flitr.jpg
    url: /projects/flitr


# paginate: 10
email: "jeremy@craftbyzen.com"
github: https://github.com/jermspeaks/jermspeaks.github.io
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax

# Build Settings
markdown: kramdown
permalink: /:title/
exclude: [README.markdown, Makefile]
timezone: UTC
encoding: utf-8
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000"
# gems: []
# sass:
#   sass_dir: _sass
gems:
  - jekyll-assets
assets:
  compress:
    css: false
    js: false
  cache: .asset-cache
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - "_assets/folder"

# collections:
#   letters:
#     output: true
#     permalink: /letters/:path/
