# site information
authors: "Jeremy Wong"
description: "© 2017 Craft By Zen"
github_username: "jermspeaks"
twitter_username: "jermspeaks"
email: "jeremy@craftbyzen.com"
navigation:
# - text: Home
#   url: /
# - text: Letter Archive
#   url: /letters/
# - text: Blog
#   url: /blog/
# - text: Resume
#   url: /resume/
- text: About
  url: /about/
- text: Writing
  url: /writing/
- text: Codes
  url: /projects/
- text: Talks
  url: /talks/

collections:
  products:
    output: true
  abouts:
    output: true

# Public API Key
snipcart_api_key: MTBmZTE2YTMtNGVhZC00ZGNmLWE5NGEtZTMwZmUwYTdlNjcyNjM2MjY2Njc2MzczMjc1NTM3

projects:
  - name: Zika VR
    description: As part of National Day of Civic Hacking 2016,
      we formed a team that created a virtual reality prototype
      to enable the public to better learn about the Zika virus –
      the nature of the pathogen, its health consequences,
      potential breeding grounds of Zika infected mosquitos,
      and effective Zika prevention techniques.
    project_link: https://jermspeaks.github.io/webvr-demo/?polyfill=1
    image: /assets/images/webvr-demo.png
    url: /projects/zika
  - name: Coral Reef Game
    description: Board game to teach children about coral reefs.
      Project from Science Hack Day 2015
    # project_link: https://github.com/jermspeaks/coral-reef-game
    # image: /assets/images/flitr.jpg
    # url: /projects/ng-pacman
  - name: Pac Man Neurohack Game
    description: Uses your brain waves to control Pacman.
      Entry to Neurogaming Hackathon 2015.
    # project_link: https://github.com/jermspeaks/NGHack-Pacman
    # image: /assets/images/flitr.jpg
    # url: /projects/ng-pacman
  - name: Under Groundwater Hack
    description: Underwater groundwater device that allows you to determine
      where there is groundwater using everyday equipment.
      Useful for digging for wells in your backyard.
      Project from Science Hack Day 2014
    # project_link: https://github.com/jermspeaks/coral-reef-game
    # image: /assets/images/flitr.jpg
    # url: /projects/ng-pacman
  - name: Remembrance
    description: Remembrance is the final project of Dev Bootcamp Chicago students
      Simon Gondeck, Francisco Scala, Jeremy Wong and Jonathan Young.
      It is a web application that enables one to create a memorial
      for a loved one who has passed on.
      You can invite friends and family to come together here and share memories,
      whether they be stories or pictures.
    project_link: http://remembrance-dbc.herokuapp.com/
    # image: /assets/images/flitr.jpg
    # url: /projects/remembrance
  - name: Flitr
    description: Flight is a social networking playground
      where users post their profiles and show their pictures.
      It is the penultimate project with DevBootcamp
    # project_link: https://github.com/simongondeck/flight-social-network
    # image: /assets/images/flitr.jpg
    # url: /projects/flitr

# Build Settings
markdown: kramdown
permalink: /:title/
exclude: [README.markdown, Makefile]
timezone: UTC
encoding: utf-8
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jermspeaks.github.io"
gems: []
sass:
  sass_dir: _sass
